### ISSUE TITLE
9092端口报错 缺少dist/index.html

### ISSUE THREAD

**Issue by ciweiin** [IceInTheFire/timotaoshu#5]
Error: ENOENT: no such file or directory, open '/www/git/timotaoshu/iview-admin-dev/dist/index.html'
    at Object.fs.openSync (fs.js:646:18)
    at Object.fs.readFileSync (fs.js:551:33)
    at /www/git/timotaoshu/iview-admin-dev/server/server.js:64:19
    at Layer.handle [as handle_request] (/www/git/timotaoshu/iview-admin-dev/server/node_modules/express/lib/router/layer.js:95:5)
    at next (/www/git/timotaoshu/iview-admin-dev/server/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/www/git/timotaoshu/iview-admin-dev/server/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/www/git/timotaoshu/iview-admin-dev/server/node_modules/express/lib/router/layer.js:95:5)
    at /www/git/timotaoshu/iview-admin-dev/server/node_modules/express/lib/router/index.js:281:22
    at param (/www/git/timotaoshu/iview-admin-dev/server/node_modules/express/lib/router/index.js:354:14)
    at param (/www/git/timotaoshu/iview-admin-dev/server/node_modules/express/lib/router/index.js:365:14)

**Comment by Allure-eve** [comment]
是否在iview-admin-dev 执行npm run build?

**Comment by IceInTheFire** [comment]
需要npm run build一下
